// Code generated by MockGen. DO NOT EDIT.
// Source: ./utility/nocover/user_input_utility.go
//
// Generated by this command:
//
//	mockgen -source=./utility/nocover/user_input_utility.go -destination=./utility/nocover/mock/mock_user_input_utility.go
//

// Package mock_utility is a generated GoMock package.
package mock_utility

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserInputUtility is a mock of UserInputUtility interface.
type MockUserInputUtility struct {
	ctrl     *gomock.Controller
	recorder *MockUserInputUtilityMockRecorder
}

// MockUserInputUtilityMockRecorder is the mock recorder for MockUserInputUtility.
type MockUserInputUtilityMockRecorder struct {
	mock *MockUserInputUtility
}

// NewMockUserInputUtility creates a new mock instance.
func NewMockUserInputUtility(ctrl *gomock.Controller) *MockUserInputUtility {
	mock := &MockUserInputUtility{ctrl: ctrl}
	mock.recorder = &MockUserInputUtilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInputUtility) EXPECT() *MockUserInputUtilityMockRecorder {
	return m.recorder
}

// InputGuessNumber mocks base method.
func (m *MockUserInputUtility) InputGuessNumber() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputGuessNumber")
	ret0, _ := ret[0].(int)
	return ret0
}

// InputGuessNumber indicates an expected call of InputGuessNumber.
func (mr *MockUserInputUtilityMockRecorder) InputGuessNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputGuessNumber", reflect.TypeOf((*MockUserInputUtility)(nil).InputGuessNumber))
}
