name: Run Tests and Generate Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

# Unittestの結果を表示する際にこの設定がないと権限エラーが出ます。
permissions: write-all

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.7

      - name: Get dependencies
        run: go mod tidy

      # Go純正のツールだとGithub ActionsのCIと相性が悪そうなのでXML形式で出力してくれるものを使います。
      - name: Setup go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Test
        run: go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: report.xml

  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.7

      - name: Get dependencies
        run: go mod tidy

      - name: Test and Coverage
        run: go test -v ./... -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
